---
> # **_데이터 다듬기_**
> - 데이터 합치기
> - 재형성과 피벗
> - 데이터 변형
---

---
> ### **데이터 합치기**
> - merge
> - concat
> - combine_first
---

### **merge**
- default : 내부조인(inner join)
- how 인자로 left, right, outer 수행가능
- 색인도 merge key가 될 수 있다

In [1]:
import pandas as pd
import numpy as np

#### **inner join**

In [2]:
df1 = pd.DataFrame({'key' : ['b','b','a','c','a','a','b'],
                    'data1' :range(7)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [3]:
df2 = pd.DataFrame({'key' :['a','b','d'],
                    'data2' : range(3)})
df2

key  data2
0   a      0
1   b      1
2   d      2

In [4]:
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [5]:
pd.merge(df1,df2,on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

#### **공통된 칼럼이 없는 경우**
- 따로 정해줌

In [6]:
df3 = pd.DataFrame({'lkey' : ['b','b','a','c','a','a','b'],
                    'data1': range(7)})
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [7]:
df4 = pd.DataFrame({'rkey' : ['a','b','d'],
                   'data2': range(3)})
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [8]:
pd.merge(df3,df4,left_on = 'lkey',right_on ='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

#### **outer join**

In [9]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [10]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [11]:
pd.merge(df1,df2,how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

#### **left join**

In [12]:
df1 = pd.DataFrame({'key' : ['b','b','a','c','a','b'],
                    'data1': range(6)})
df2 = pd.DataFrame({'key' : ['a','b','a','b','d'],
                    'data2': range(5)})

In [13]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [14]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [15]:
pd.merge(df1,df2,on='key',how='left')

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

#### **right join**

In [16]:
pd.merge(df1,df2, on ='key',how='right')

key  data1  data2
0    a    2.0      0
1    a    4.0      0
2    b    0.0      1
3    b    1.0      1
4    b    5.0      1
5    a    2.0      2
6    a    4.0      2
7    b    0.0      3
8    b    1.0      3
9    b    5.0      3
10   d    NaN      4

#### **색인 merge**

In [17]:
left1 = pd.DataFrame({'key' :['a','b','a','a','b','c'],
                      'value' : range(6)})
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [18]:
right1 = pd.DataFrame({'group_val':[3.5,7]}, index = ['a','b'])
right1

group_val
a        3.5
b        7.0

#### 교집합
- right1의 index를 key값으로 색인해줌

In [19]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

#### 외부조인

In [20]:
pd.merge(left1,right1,left_on='key',right_index=True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

### **concat**
- numpy : concatenate
- pandas : concat(Series, DF, axis인자, join_axes인자, keys 인자, ignore_index 인자

#### **concatenate**

In [21]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.concatenate([arr,arr],axis=1) 

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

#### **concat**
#### Series

In [23]:
s1 = pd.Series([0,1], index=['a','b'])
s2 = pd.Series([2,3,4], index=['c','d','e'])
s3 = pd.Series([5,6], index=['f','g'])

In [24]:
s1

a    0
b    1
dtype: int64

In [25]:
s2

c    2
d    3
e    4
dtype: int64

In [26]:
s3

f    5
g    6
dtype: int64

In [27]:
pd.concat([s1,s2,s3]) #default 는 axis = 0

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [28]:
pd.concat([s1,s2,s3],axis =1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [29]:
s4 = pd.concat([s1*5,s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

#### DataFrame

In [30]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2), index= ['a','b','c'],
                   columns= ['one','two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2,2), index = ['a','c'],
                  columns= ['three','four'])

In [31]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [32]:
df2

three  four
a      5     6
c      7     8

In [33]:
pd.concat([df1,df2])

one  two  three  four
a  0.0  1.0    NaN   NaN
b  2.0  3.0    NaN   NaN
c  4.0  5.0    NaN   NaN
a  NaN  NaN    5.0   6.0
c  NaN  NaN    7.0   8.0

In [34]:
pd.concat([df1,df2],axis=1)

one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

In [35]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

#### combine_first
- 두 객체를 포개서 한 객체에서 누락된 데이터를 다른 객체에 있는 값으로 채움

#### Series

In [36]:
a = pd.Series([np.nan, 2.5,np.nan,3.5,4.5,np.nan], index = ['f','e','d','c','h','a'])
a

f    NaN
e    2.5
d    NaN
c    3.5
h    4.5
a    NaN
dtype: float64

In [37]:
b = pd.Series(np.arange(len(a), dtype=np.float64), index = ['f','e','d','c','b','a'])
b[-1] = np.nan
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [38]:
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

#### 결측치가 있는 부분만 채워넣음

In [39]:
b[:-2]

f    0.0
e    1.0
d    2.0
c    3.0
dtype: float64

In [40]:
a[2:]

d    NaN
c    3.5
h    4.5
a    NaN
dtype: float64

In [41]:
b[:-2].combine_first(a[2:])

a    NaN
c    3.0
d    2.0
e    1.0
f    0.0
h    4.5
dtype: float64

#### DataFrame

In [42]:
df1 = pd.DataFrame({'a':[1.,np.nan,5.,np.nan],
                    'b':[np.nan, 2., np.nan, 6.],
                    'c':range(2,18,4)})
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [43]:
df2 = pd.DataFrame({'a' :[5.,4.,np.nan,3.,7],
                    'b' :[np.nan,3.,4.,6.,8.]})
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [44]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

---
> ### **재형성과 피벗**
> - 표 형식의 데이터를 재배치 : reshaping, 피벗
> - 계층적 색인으로 재형성
> - 피버팅
---

### **계층적 색인으로 재형성**
- stack : 데이터의 컬럼을 로우로 피벗 또는 회전
- unstack : 로우를 칼럼으로 피벗

In [45]:
data = pd.DataFrame(np.arange(6).reshape(2,3),
                    index = pd.Index(['Ohio','Colorado'],name= 'state'),
                    columns = pd.Index(['one','two','three'], name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [46]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [47]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

### **피버팅**

In [48]:
ldata = pd.DataFrame({'date' :np.random.rand(9),
                      'item': ['a','a','c','b','a','b','c','a','a'],
                      'value' : np.arange(9)})
ldata

date item  value
0  0.566891    a      0
1  0.323909    a      1
2  0.222456    c      2
3  0.998486    b      3
4  0.264609    a      4
5  0.595157    b      5
6  0.466651    c      6
7  0.873970    a      7
8  0.031546    a      8

In [49]:
pivoted = ldata.pivot('date','item','value')
pivoted.head()

C:\Users\skyme\AppData\Local\Temp\ipykernel_22100\2581443392.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  pivoted = ldata.pivot('date','item','value')


item        a   b    c
date                  
0.031546  8.0 NaN  NaN
0.222456  NaN NaN  2.0
0.264609  4.0 NaN  NaN
0.323909  1.0 NaN  NaN
0.466651  NaN NaN  6.0

---
> ### **데이터 변형**
---

### **중복제거**

In [50]:
data= pd.DataFrame({'k1':['one']*3 + ['two']*4,
                    'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [51]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [52]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

### **함수 매핑**

In [53]:
data = pd.DataFrame({'food' :['bacon','pulled pork','bacon','Pastrami',
                              'corned beef','Bacon','pastrami','honey ham','nova lox'],
                     'ounces':[4,3,12,6,7.5,8,3,5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [54]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork' :'pig',
    'pastrami' :'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox' : 'salmon'
}

In [55]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [56]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### **값 치환**

In [57]:
data = pd.Series([1.,-999.,2.,-999,-1000.,3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [58]:
data.replace(-999,np.nan,inplace = True)
data

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

### **특이값 찾고 치환하기**

In [59]:
np.random.seed(12345)
data = pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [60]:
col = data[3]
col.head()

0   -0.555730
1    0.281746
2   -1.296221
3    0.886429
4   -0.438570
Name: 3, dtype: float64

In [61]:
col[np.abs(col) > 3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

- **절대값이 3이 넘는 값이 하나라도 있는 행**은 모두 출력한다는 의미

In [62]:
data[(np.abs(data)>3).any(1)]

C:\Users\skyme\AppData\Local\Temp\ipykernel_22100\2768852463.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  data[(np.abs(data)>3).any(1)]


0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

---
> ### **데이터 그룹 연산**
> - 그룹 연산 = 분리-적용-결합
---

In [63]:
df = pd.DataFrame({'key1':['a','a','b','b','a'],
                'key2':['one','two','one','two','one'],
                'data1':np.random.randn(5),
                'data2':np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  1.150765  1.199915
1    a  two -0.997174 -0.451814
2    b  one  0.046486 -0.155385
3    b  two -0.610441 -0.153514
4    a  one -0.394982  0.011194

In [64]:
grouped = df['data1'].groupby(df['key1'])
grouped

In [65]:
grouped.mean()

key1
a   -0.080463
b   -0.281977
Name: data1, dtype: float64

In [66]:
means = df['data1'].groupby([df['key1'],df['key2']]).mean()
means

key1  key2
a     one     0.377892
      two    -0.997174
b     one     0.046486
      two    -0.610441
Name: data1, dtype: float64