## 데이터 프레임
### pd.Dataframe 또는 csv 파일 읽기

In [1]:
import pandas as pd
import numpy as np

### 데이터 추가

In [2]:
df = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]])); display(df)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [3]:
df.loc[3]=[10,11,12]; display(df)

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [4]:
df= df.append([[10,11,12]],ignore_index =True); display(df)

C:\Users\skyme\AppData\Local\Temp\ipykernel_20268\2840986873.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df= df.append([[10,11,12]],ignore_index =True); display(df)


0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  10  11  12

### 컬럼추가

In [5]:
df.columns = list("ABC")

In [6]:
display(df)

A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  10  11  12

In [7]:
df["D"] = list("ddddd"); display(df) 

A   B   C  D
0   1   2   3  d
1   4   5   6  d
2   7   8   9  d
3  10  11  12  d
4  10  11  12  d

In [8]:
df[4] = [4]*5; display(df)

A   B   C  D  4
0   1   2   3  d  4
1   4   5   6  d  4
2   7   8   9  d  4
3  10  11  12  d  4
4  10  11  12  d  4

In [9]:
df[7] = [7]*5; display(df)

A   B   C  D  4  7
0   1   2   3  d  4  7
1   4   5   6  d  4  7
2   7   8   9  d  4  7
3  10  11  12  d  4  7
4  10  11  12  d  4  7

### 데이터 삭제

In [10]:
df = df.drop(7,axis = 1); display(df) #컬럼삭제

A   B   C  D  4
0   1   2   3  d  4
1   4   5   6  d  4
2   7   8   9  d  4
3  10  11  12  d  4
4  10  11  12  d  4

In [11]:
df = df.drop([4,'D'],axis=1); display(df) # 다중컬럼 삭제

A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  10  11  12

In [12]:
df= df.drop(4,axis =0); display(df) # 행 삭제

A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [13]:
df = df.drop([2,3], axis =0); display(df) # 다중행 삭제

A  B  C
0  1  2  3
1  4  5  6

### 데이터 변경

In [14]:
df.loc[0][0] =100; display(df)

A  B  C
0  100  2  3
1    4  5  6

In [15]:
df.loc[0]["B"] = 100; display(df)

A    B  C
0  100  100  3
1    4    5  6

In [16]:
df.iloc[1][1] = 100; display(df)

A    B  C
0  100  100  3
1    4  100  6

In [17]:
df.iloc[1]["C"] = 100; display(df)

A    B    C
0  100  100    3
1    4  100  100

In [18]:
df.iloc[0][0:2] = [1,2]; display(df)

A    B    C
0  1    2    3
1  4  100  100

In [19]:
df.loc[3] = [1,2,5]; display(df) # 행추가할 때는 loc 사용

A    B    C
0  1    2    3
1  4  100  100
3  1    2    5

In [20]:
df["C"]

0      3
1    100
3      5
Name: C, dtype: int64

In [21]:
df["C"] = [3,6,9]; display(df)

A    B  C
0  1    2  3
1  4  100  6
3  1    2  9

In [22]:
df.loc['D'] = [12,6,18]; display(df) #행추가

A    B   C
0   1    2   3
1   4  100   6
3   1    2   9
D  12    6  18

In [23]:
df= df.reset_index(drop=True); display(df)

A    B   C
0   1    2   3
1   4  100   6
2   1    2   9
3  12    6  18

In [24]:
df.loc[0]['A'] = 100; display(df)

A    B   C
0  100    2   3
1    4  100   6
2    1    2   9
3   12    6  18

In [25]:
df["D"] = [8,6,1,10]; display(df)

A    B   C   D
0  100    2   3   8
1    4  100   6   6
2    1    2   9   1
3   12    6  18  10

In [26]:
df.iloc[1:,2:]

C   D
1   6   6
2   9   1
3  18  10

### 데이터 정렬

In [27]:
df = pd.DataFrame({"cluster":[1,1,2,1,2,3], 'org':['a','a','h','c','d','w'], "time": [8,6,34,23,74,6]});display(df)

cluster org  time
0        1   a     8
1        1   a     6
2        2   h    34
3        1   c    23
4        2   d    74
5        3   w     6

In [28]:
df= df.sort_values(['time'],ascending =[False]); display(df)

cluster org  time
4        2   d    74
2        2   h    34
3        1   c    23
0        1   a     8
1        1   a     6
5        3   w     6

In [29]:
df = df.reset_index(drop=True); display(df)

cluster org  time
0        2   d    74
1        2   h    34
2        1   c    23
3        1   a     8
4        1   a     6
5        3   w     6

### 함수

In [30]:
df = pd.DataFrame({'cluseter':[1,1,2,1,2,3],'org':['a','a','h','c','d','w'],'time':[8,6,34,23,74,6]}); display(df)

cluseter org  time
0         1   a     8
1         1   a     6
2         2   h    34
3         1   c    23
4         2   d    74
5         3   w     6

In [31]:
df.describe()

cluseter       time
count  6.000000   6.000000
mean   1.666667  25.166667
std    0.816497  26.445542
min    1.000000   6.000000
25%    1.000000   6.500000
50%    1.500000  15.500000
75%    2.000000  31.250000
max    3.000000  74.000000

In [32]:
df.head(2)

cluseter org  time
0         1   a     8
1         1   a     6

In [33]:
df.tail(2)

cluseter org  time
4         2   d    74
5         3   w     6

In [34]:
df.T

0  1   2   3   4  5
cluseter  1  1   2   1   2  3
org       a  a   h   c   d  w
time      8  6  34  23  74  6

In [35]:
df.time

0     8
1     6
2    34
3    23
4    74
5     6
Name: time, dtype: int64

In [36]:
df[df.time<10]

cluseter org  time
0         1   a     8
1         1   a     6
5         3   w     6

### 도전문제 6.1

In [37]:
month_se = pd.Series(["1월","2월",'3월','4월'])
income_se = pd.Series([9500, 6200, 6050, 7000])
expenses_se = pd.Series([5040,2350,2300,4800])
df = pd.DataFrame({"월": month_se, '수익':income_se,'지출': expenses_se})
df

월    수익    지출
0  1월  9500  5040
1  2월  6200  2350
2  3월  6050  2300
3  4월  7000  4800

In [38]:
print("동윤이네 상점의 수입합계: {:,}".format(df['수익'].sum()))
print("동윤이네 상점의 지출합계: {:,}".format(sum(df['지출'])))

동윤이네 상점의 수입합계: 28,750
동윤이네 상점의 지출합계: 14,490


### 데이터프레임의 구조

In [39]:
df.columns

Index(['월', '수익', '지출'], dtype='object')

In [40]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [41]:
df['total'] = df.sum(axis=1)
df

C:\Users\skyme\AppData\Local\Temp\ipykernel_20268\2156962985.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df['total'] = df.sum(axis=1)


월    수익    지출  total
0  1월  9500  5040  14540
1  2월  6200  2350   8550
2  3월  6050  2300   8350
3  4월  7000  4800  11800

In [42]:
df.loc[4] = ["총월합계",sum(df["수익"]),sum(df["지출"]),sum(df['total'])]
df

월     수익     지출  total
0    1월   9500   5040  14540
1    2월   6200   2350   8550
2    3월   6050   2300   8350
3    4월   7000   4800  11800
4  총월합계  28750  14490  43240

In [43]:
df.loc[3]

월           4월
수익        7000
지출        4800
total    11800
Name: 3, dtype: object

### 시험
### 퀴즈 8일차

In [44]:
import numpy as np
import pandas as pd

#### 1번

In [45]:
a = np.array([0,10,20,40,60,80])
b = np.array([0,20])
c = np.setdiff1d(a, b)
c

array([10, 40, 60, 80])

#### 다른 풀이

In [46]:
a = np.array([0,10,20,40,60,80])
b = np.array([0,20])
c = np.array([],dtype =int)
for i in range(len(a)):
    if a[i] not in b:
        c = np.append(c,a[i])
print(c)

[10 40 60 80]


#### 2번

In [47]:
a = np.arange(1,11)
a = a.reshape(10,1)
a

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

#### 3번

In [48]:
a[::-1]

array([[10],
       [ 9],
       [ 8],
       [ 7],
       [ 6],
       [ 5],
       [ 4],
       [ 3],
       [ 2],
       [ 1]])

#### 4번

In [49]:
a = np.arange(10,26)
a = a.reshape(4,4)
print("배열 a:\n", a)
print("각 행의 합:", a.sum(axis=1))
print("각 열의 합:", a.sum(axis=0))

배열 a:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
각 행의 합: [46 62 78 94]
각 열의 합: [64 68 72 76]


#### 5번

In [50]:
x = np.array([10,20,40,60,10,20,40,40,40])
unique,counts = np.unique(x,return_counts=True)
uniq_dict = dict(zip(unique,counts))
for i in uniq_dict.keys():
    print(i,":",uniq_dict[i],'번')

10 : 2 번
20 : 2 번
40 : 4 번
60 : 1 번


#### 6번

In [51]:
array1 = np.arange(5)
print("처음 array는 1차원 배열:\n",array1)
array1 = array1.reshape(1,5)
print("reshape 를 통해 바꾼 후 2차원 배열:\n",array1)

처음 array는 1차원 배열:
 [0 1 2 3 4]
reshape 를 통해 바꾼 후 2차원 배열:
 [[0 1 2 3 4]]


#### 7번

In [52]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print("처음 array3d는 3차원 배열:\n",array3d)
array2d = array3d.reshape(2,-1)
print("reshape를 통해 바꾼 후 2차원 배열 array2d:\n", array2d)

처음 array3d는 3차원 배열:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
reshape를 통해 바꾼 후 2차원 배열 array2d:
 [[0 1 2 3]
 [4 5 6 7]]


#### 8번

In [53]:
n = int(input("n을 입력하시오:"))
a = np.eye(n,dtype =int)
for i in range(n):
    for j in range(n):
        if i >= j:
            a[i][j] = 1
print(a)

n을 입력하시오: 5


[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


#### 9번

In [55]:
array2d = np.array([[1,2,3], [4,5,6],[7,8,9]])
array2d[2,1:]

array([8, 9])

#### 10번

In [56]:
name = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score = np.array([22, 44, 84, 10, 88])
dict1 = dict(zip(name,score))
print("기존 dict1:",dict1)
new_dict1 = sorted(dict1.items(), key=lambda x:x[1], reverse= True)
print("정렬된 dict1:",new_dict1)

기존 dict1: {'John': 22, 'Mike': 44, 'Sarah': 84, 'Kate': 10, 'Samuel': 88}
정렬된 dict1: [('Samuel', 88), ('Sarah', 84), ('Mike', 44), ('John', 22), ('Kate', 10)]


## 시험! 12월 23일 금

#### 1번

In [57]:
def temp(celsius):
    fahrenheit = (9/5) * celsius + 32
    return fahrenheit
print("섭씨 10 도 = 화씨", temp(10))
print("섭씨 20 도 = 화씨", temp(20))
print("섭씨 30 도 = 화씨", temp(30))
print("섭씨 40 도 = 화씨", temp(40))
print("섭씨 50 도 = 화씨", temp(50))

섭씨 10 도 = 화씨 50.0
섭씨 20 도 = 화씨 68.0
섭씨 30 도 = 화씨 86.0
섭씨 40 도 = 화씨 104.0
섭씨 50 도 = 화씨 122.0


#### 2번

In [58]:
a = [1, 2, 3, 4, 5, 6, 7]
b = [x ** 2 for x in a]
b

[1, 4, 9, 16, 25, 36, 49]

#### 3번

In [59]:
def print_area(width,height):
    print("밑변 {}, 높이 {}인 삼각형의 면적은 : {}".format(width, height, int(width*height/2)))

print_area(10, 20)

밑변 10, 높이 20인 삼각형의 면적은 : 100


#### 4번

In [60]:
print('Hello','Python', '!')

Hello Python !


#### 5번

In [61]:
#(1) Print('Hello Python!')
print('Hello Python!')  # print 소문자

#(2) print("Hello Python!')
print('Hello Python!') # 문자열 출력 시 공통되게 작은 따음표 또는 큰따음표 사용

#(3) print(Hello Python!)
print('Hello Python!') # 따음표가 없으므로 넣어줘야 함

#(4) print(100 + '200')
print(100 + 200) # 숫자는 따음표를 쓰지 않음

#(5) print('3의 3제곱 :', 3 ^ 3)
print('3의 3제곱 :', 3**3) # 파이썬의 제곱근 기호는 **임


Hello Python!
Hello Python!
Hello Python!
300
3의 3제곱 : 27


#### 6번

In [63]:
r = int(input("원의 반지름을 입력하세요 : "))
PI = 3.141592
print("원의 둘레 = {}, 원의 면적 = {}".format(2*PI*r, PI*r**2))

원의 반지름을 입력하세요 :  11


원의 둘레 = 69.115024, 원의 면적 = 380.132632


#### 7번

In [64]:
n = int(input("정수를 입력하세요 : "))
if 0<=n<=100:
    print("입력된 정수는 0에서 100의 범위 안에 있는 짝수인가요? True")
else:
    print("입력된 정수는 0에서 100의 범위 안에 있는 짝수인가요? False")

정수를 입력하세요 :  120


입력된 정수는 0에서 100의 범위 안에 있는 짝수인가요? False


#### 8번

In [65]:
a = int(input("정수 a를 입력하세요 : "))
b = int(input("정수 b를 입력하세요 : "))
print("a / b의 몫 : {}".format(a//b))
print("a / b의 나머지 : {}".format(a%b))

정수 a를 입력하세요 :  202
정수 b를 입력하세요 :  50


a / b의 몫 : 4
a / b의 나머지 : 2


#### 9번

In [66]:
n = input("이름을 입력하시오 : ")
h = int(input("키를 입력하시오(단위 cm) : "))
if h < 140:
    print("{}님은 놀이기구를 탈 수 없습니다.".format(n))
else:
    print("{}님은 놀이기구를 탈 수 있습니다.".format(n))

이름을 입력하시오 :  동윤
키를 입력하시오(단위 cm) :  160


동윤님은 놀이기구를 탈 수 있습니다.


#### 10번

In [67]:
list_ex = [10, 20, 30, 40, 50, 60, 70]
list_ex[-1] #답

70

#### 11번
#### 답 : x o x

#### 12번

In [68]:
a = dict()
a['name']='python' # (1) 오류 안남

In [69]:
a = dict()
a[('a',)] = 'python' # (2) 오류 안남

In [70]:
a = dict()
# a[[1]]='python' #(3) 오류남

In [71]:
a = dict()
a[250]='python' #(4) 오류 안남

#### 13번

In [72]:
list1 = [3, 5, 7]
list2 = [2, 3, 4, 5, 6]
for i in range(len(list1)):
    for j in range(len(list2)):
        if list1[i] == 5 and list2[j] == 3:
            break
        elif list1[i] == 7:
            break
        print("{} * {} = {}".format(list1[i],list2[j],list1[i]*list2[j]))

3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
5 * 2 = 10


#### 14번

In [73]:
table = ["Americano", "Ice Americano", "Cappuccino", "Caffe Latte", "Espresso"]
price = [3000, 3500, 4000, 4500, 3600]
menu = dict(zip(table, price))
for key in menu:
    print("{} 가격 : {}원".format(key,menu[key]) )

Americano 가격 : 3000원
Ice Americano 가격 : 3500원
Cappuccino 가격 : 4000원
Caffe Latte 가격 : 4500원
Espresso 가격 : 3600원


#### 15번

In [74]:
import math
a = np.arange(11)
for i in a:
    print("sqrt({}) = {:.4f}".format(i,math.sqrt(i)))

sqrt(0) = 0.0000
sqrt(1) = 1.0000
sqrt(2) = 1.4142
sqrt(3) = 1.7321
sqrt(4) = 2.0000
sqrt(5) = 2.2361
sqrt(6) = 2.4495
sqrt(7) = 2.6458
sqrt(8) = 2.8284
sqrt(9) = 3.0000
sqrt(10) = 3.1623


#### 16번

In [75]:
class Dog:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def __str__(self):
        return "my_dog의 이름은 {}이고 나이는 {}살입니다.".format(self.name,self.age)
    
my_dog = Dog("Mango",3)
print(my_dog)

my_dog의 이름은 Mango이고 나이는 3살입니다.


#### 17번

In [76]:
a = np.arange(1,11)
a = a.reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### 18번

In [77]:
# 18번
a = 3
b = 4
a,b = b,a 
print("a는 {}, b는 {}".format(a,b))

a는 4, b는 3


#### 19번

In [78]:
list_int = list(range(0,10))
print(list_int)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


#### 20번

In [79]:
a = [1,1,1,3,3,4,4,4,4,5]
a = list(set(a))
print(a)

[1, 3, 4, 5]
